#!/bin/bash
set -euo pipefail

# Script to set up test database environment
# Run this once to configure your test database

echo "🔧 Setting up test database environment"
echo ""

# Check if .env.test exists
if [ -f .env.test ]; then
  echo "✅ .env.test already exists"
  echo "   If you want to reconfigure, delete .env.test and run this script again"
  exit 0
fi

# Check if .env.local exists to get database credentials pattern
if [ ! -f .env.local ]; then
  echo "❌ .env.local not found. Please set up your development environment first:"
  echo "   vercel env pull .env.local"
  exit 1
fi

echo "📋 Instructions for setting up test database:"
echo ""
echo "1. Go to your Neon console: https://console.neon.tech"
echo "2. Select your project"
echo "3. Create a new database branch called 'test' or 'testing'"
echo "4. Copy the connection string for the test database"
echo ""
echo "Enter your test database connection string:"
read -r TEST_DATABASE_URL

# Validate the connection string
if [[ ! "$TEST_DATABASE_URL" =~ ^postgresql:// ]]; then
  echo "❌ Invalid connection string. Must start with postgresql://"
  exit 1
fi

# Create .env.test
cat > .env.test << EOF
# Test database configuration
# Generated by scripts/setup-test-env.sh
TEST_DATABASE_URL="${TEST_DATABASE_URL}"
EOF

echo ""
echo "✅ Created .env.test with test database configuration"
echo ""
echo "Next steps:"
echo "1. Run 'npm run test:db:init' to initialize the test database"
echo "2. Run 'npm test' to run the tests"